
/**/vesc_driver_1:
  ros__parameters:
    port: /dev/vesc_1
    baud: 115200
    duty_cycle_max: 0.9
    command_timeout_sec: 0.5
    max_current_a: 20.0
    max_rpm: 100000.0
    invert: true

/**/vesc_driver_2:
  ros__parameters:
    port: /dev/vesc_2
    baud: 115200
    duty_cycle_max: 0.9
    command_timeout_sec: 0.5
    max_current_a: 20.0
    max_rpm: 100000.0
    invert: false   
